baseurl = "https://blog.mattctl.dev"
title = "mattctl"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "mattctl"
  info = "Platform Engineer | Kubernetes Enthusiast | Homelabber"
  description = "Mattctl's Personal tech blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar-256x256.png"

  since = 2025

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/mattctl/"


# Menu links
[[menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About Me"
  weight = 1
  url = "about/"