name: Build

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.24.6'
            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                path: |
                    ~/go/pkg/mod
                    ~/go/pkg/sumdb
                key: ${{ runner.os }}-go-
            - name: Cache Go binaries
              uses: actions/cache@v4
              with:
                path: ~/go/bin
                key: ${{ runner.os }}-gobin
            - name: render site
              run: make build
            - name: push rendered site to live
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                git config --global user.name "mattctl"
                git config --global user.email "227002067+mattctl@users.noreply.github.com"
                git checkout -b live
                git rm -r .
                git add public -f
                git commit -m "site rendered from commit ${{ github.sha}} | triggered by ${{ github.actor }}."
                git push origin live --force

            